INSERT INTO CLASSROOM (id, trainer, trainees) VALUES (1, 'Matt Hunt')
INSERT INTO CLASSROOM (id, trainer, trainees) VALUES (2, 'Jordan Trainer')
INSERT INTO TRAINEE (id, traineeName) VALUES (1, 'Umayr Saghir')
INSERT INTO TRAINEE (id, traineeName) VALUES (2, 'Declan McGee')
INSERT INTO TRAINEE (id, traineeName) VALUES (3, 'Henry Chia')
INSERT INTO TRAINEE (id, traineeName) VALUES (4, 'Uzair Hayat')
INSERT INTO TRAINEE (id, traineeName) VALUES (5, 'Jason Derry')
